---
# For use with packer and ansible-local provisioner.
- hosts: all
  connection: local
  sudo: yes
  roles:
    - base
    - ntp
    - python3
  vars:
    python3_pip_packages:
      - awscli
      - boto
