# role dependencies
---
- src: git+git@github.com:ridecharge/base-ansible-role.git
  path: roles
  name: base

- src: git+git@github.com:ridecharge/ntp-ansible-role.git
  path: roles
  name: ntp

- src: git+git@github.com:ridecharge/python3-ansible-role.git
  path: roles
  name: python3

- src: git+git@github.com:ridecharge/logging-ansible-role.git
  path: roles
  name: logging
